### ISSUE TITLE
how to set the location without giving location access?

### ISSUE THREAD

**Issue by mneuschaefer** [nbolar/Weather-Status#2]
I do not want to give location access to this app. How can I set the location for the weather forecast manually? This would also be important to check the weather from somewhere else before travelling.

Currently I can only change the location _after_ enabling location services for the app. 

Can you enable manual entry for the location that does not require these permissions? 

![image](https://user-images.githubusercontent.com/11058806/57364007-8f936700-7182-11e9-8146-9396c6beb560.png)

**Comment by nbolar** [comment]
Hey! I apologize for the late response. From the screenshot it looks like you're using the App Store version, I have enabled manual entry for locations and now longer requires location access. I'll be pushing out the update as soon as I finish testing it. Look for version 1.0.9 in the Mac App Store by the end of the week. 

You'll first get the generic _**App requires location access**_ popup, once you deny access to it, another popup will be presented which will allow you to choose the option to use the app without providing location access.
