### ISSUE TITLE
Fahrenheit doesnt work.

### ISSUE THREAD

**Issue by ladoublery** [nbolar/Weather-Status#3]
When I attempt to switch the temperature from Celsius to Fahrenheit it simply stays Celsius.

**Comment by nbolar** [comment]
I just cloned this same version and ran the app. Switching between units works just fine. Do you mind providing more information? There are several changes that need to be performed in order to get the app running.

**Comment by ladoublery** [comment]
App Store version 1.0.15

**Comment by nbolar** [comment]
Sorry about the confusion. Once you click the button to switch to Fahrenheit, give it a few seconds to fetch the updated weather details. It takes a little while to download the updated data. In a future update I’ll be sure to include a loading animation to indicate that the weather details are being fetched.

**Comment by ladoublery** [comment]
![temp](https://user-images.githubusercontent.com/53904333/71136433-d3e3ec80-21d2-11ea-8f6c-45fa5a77422c.gif)

**Comment by nbolar** [comment]
I’ve just pushed two updates to the App Store that should hopefully fix this issue. Do you mind updating the App and then try switching units?

**Comment by ladoublery** [comment]
Same result with 1.0.17

**Comment by nbolar** [comment]
Can you post another screen recording please? I want to know whether the loading animation continues to persist or not.

**Comment by ladoublery** [comment]
![test2](https://user-images.githubusercontent.com/53904333/71208652-7b1a5f80-2277-11ea-8e77-db77a4031729.gif)

**Comment by nbolar** [comment]
Okay so I figured out the issue and will be pushing a fix today. Here's what it should look like when switching between units:




![Screen Recording 2019-12-20 at 8 05 08 AM 480 2019-12-20 08_44_31](https://user-images.githubusercontent.com/45484873/71232936-fece5d80-2304-11ea-8730-65b1ba99f881.gif)

**Comment by nbolar** [comment]
Version 1.0.18 is now live and should fix the issue.

**Comment by ladoublery** [comment]
sorry for the late reply, the issue is indeed fixed, thank you
